server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: gallery
          uri: http://172.17.0.1:8081
          predicates:
            - Path=/api/gallery
        - id: image
          uri: http://172.17.0.1:8082
          predicates:
            - Path=/api/image/*
        - id: eureka
          uri: http://172.17.0.1:8761
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
        - id: eureka_server_static
          uri: http://172.17.0.1:8761
          predicates:
            - Path=/eureka/**

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 172.17.0.1
  client:
    service-url:
      defaultZone: http://172.17.0.1:8761/eureka/

# set log
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
