server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: gallery
          uri: lb://gallery
          predicates:
            - Path=/api/gallery
        - id: image
          uri: lb://image
          predicates:
            - Path=/api/image
        - id: eureka
          uri: http://localhost:8761
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
        - id: eureka_server_static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

# set log
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
