server:
  port: 8081

spring:
  application:
    name: gallery
  r2dbc:
    url: r2dbc:postgresql://localhost/gallery?createDatabaseIfNotExist=true
    username: postgres
    password: secret

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
