server:
  port: 0

spring:
  application:
    name: gallery
  r2dbc:
    url: r2dbc:mysql://172.17.0.1:3306/gallery
    username: root
    password: secret

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 172.17.0.1
  client:
    service-url:
      defaultZone: http://172.17.0.1:8761/eureka/
