server:
  port: 8088

spring:
  application:
    name: gallery
  r2dbc:
    url: r2dbc:mysql://localhost:3307
    name: gallery
    username: root
    password: secret

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
