server:
  port: 8083

spring:
  application:
    name: image
    r2dbc:
      url: r2dbc:mysql://127.0.0.1/image
      username: root
      password: secret

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
