server:
  port: 8082

spring:
  application:
    name: image
  r2dbc:
    url: r2dbc:postgresql://localhost:8090/image?createDatabaseIfNotExist=true
    username: postgres
    password: secret

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
