server:
  port: 8082

spring:
  application:
    name: image
  r2dbc:
    url: r2dbc:mysql://localhost:3306
    name: image
    username: root
    password: secret

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
