server:
  port: 8082

spring:
  application:
    name: image

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 172.17.0.1
  client:
    service-url:
      defaultZone: http://172.17.0.1:8761/eureka/
